twig:
    default_path: "%kernel.project_dir%/templates"
    globals:
        locales: "%app.locales%"
        webSiteName: "%webSiteName%"
        currency: "%currency%"
when@test:
    twig:
        strict_variables: true
