#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_productcustomer_show:
    path:     /customer/product/{id}    
    defaults: { _controller:  App\Controller\ProductCustomerController::show }
    methods:   [POST, GET]


